# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Card.destroy_all

Card.create(suit: "Pine", type: nil, sub_type: nil, img_src: "./../app/assets/images/1.png")
Card.create(suit: "Pine", type: nil, sub_type: nil, img_src: "./../app/assets/images/2.png")
Card.create(suit: "Pine", type: "Ribbon", sub_type: "Poem", img_src: "./../app/assets/images/3.png")
Card.create(suit: "Pine", type: "Bright", sub_type: nil, img_src: "./../app/assets/images/4.png")
Card.create(suit: "Plum Blossoms", type: nil, sub_type: nil, img_src: "./../app/assets/images/5.png")
Card.create(suit: "Plum Blossoms", type: nil, sub_type: nil, img_src: "./../app/assets/images/6.png")
Card.create(suit: "Plum Blossoms", type: "Ribbon", sub_type: "Poem", img_src: "./../app/assets/images/7.png")
Card.create(suit: "Plum Blossoms", type: "Animal", sub_type: nil, img_src: "./../app/assets/images/8.png")
Card.create(suit: "Cherry Blossoms", type: nil, sub_type: nil, img_src: "./../app/assets/images/9.png")
Card.create(suit: "Cherry Blossoms", type: nil, sub_type: nil, img_src: "./../app/assets/images/10.png")
Card.create(suit: "Cherry Blossoms", type: "Ribbon", sub_type: "Poem", img_src: "./../app/assets/images/11.png")
Card.create(suit: "Cherry Blossoms", type: "Bright", sub_type: nil, img_src: "./../app/assets/images/12.png")
Card.create(suit: "Wisteria", type: nil, sub_type: nil, img_src: "./../app/assets/images/13.png")
Card.create(suit: "Wisteria", type: nil, sub_type: nil, img_src: "./../app/assets/images/14.png")
Card.create(suit: "Wisteria", type: "Ribbon", sub_type: nil, img_src: "./../app/assets/images/15.png")
Card.create(suit: "Wisteria", type: "Animal", sub_type: nil, img_src: "./../app/assets/images/16.png")
Card.create(suit: "Iris", type: nil, sub_type: nil, img_src: "./../app/assets/images/17.png")
Card.create(suit: "Iris", type: nil, sub_type: nil, img_src: "./../app/assets/images/18.png")
Card.create(suit: "Iris", type: "Ribbon", sub_type: nil, img_src: "./../app/assets/images/19.png")
Card.create(suit: "Iris", type: "Animal", sub_type: nil, img_src: "./../app/assets/images/20.png")
Card.create(suit: "Peony", type: nil, sub_type: nil, img_src: "./../app/assets/images/21.png")
Card.create(suit: "Peony", type: nil, sub_type: nil, img_src: "./../app/assets/images/22.png")
Card.create(suit: "Peony", type: "Ribbon", sub_type: "Blue", img_src: "./../app/assets/images/23.png")
Card.create(suit: "Peony", type: "Animal", sub_type: "Butterfly", img_src: "./../app/assets/images/24.png")
Card.create(suit: "Bush Clover", type: nil, sub_type: nil, img_src: "./../app/assets/images/25.png")
Card.create(suit: "Bush Clover", type: nil, sub_type: nil, img_src: "./../app/assets/images/26.png")
Card.create(suit: "Bush Clover", type: "Ribbon", sub_type: nil, img_src: "./../app/assets/images/27.png")
Card.create(suit: "Bush CLover", type: "Animal", sub_type: "boar", img_src: "./../app/assets/images/28.png")
Card.create(suit: "Silver Grass", type: nil, sub_type: nil, img_src: "./../app/assets/images/29.png")
Card.create(suit: "Silver Grass", type: nil, sub_type: nil, img_src: "./../app/assets/images/30.png")
Card.create(suit: "Silver Grass", type: "Animal", sub_type: nil, img_src: "./../app/assets/images/31.png")
Card.create(suit: "Silver Grass", type: "Bright", sub_type: nil, img_src: "./../app/assets/images/32.png")
Card.create(suit: "Chrysanthemum", type: nil, sub_type: nil, img_src: "./../app/assets/images/33.png")
Card.create(suit: "Chrysanthemum", type: nil, sub_type: nil, img_src: "./../app/assets/images/34.png")
Card.create(suit: "Chrysanthemum", type: "Ribbon", sub_type: "blue", img_src: "./../app/assets/images/35.png")
Card.create(suit: "Chrysanthemum", type: "Animal", sub_type: nil, img_src: "./../app/assets/images/36.png")
Card.create(suit: "Maple", type: nil, sub_type: nil, img_src: "./../app/assets/images/37.png")
Card.create(suit: "Maple", type: nil, sub_type: nil, img_src: "./../app/assets/images/38.png")
Card.create(suit: "Maple", type: "Ribbon", sub_type: "Blue", img_src: "./../app/assets/images/39.png")
Card.create(suit: "Maple", type: "Animal", sub_type: "Deer", img_src: "./../app/assets/images/40.png")
Card.create(suit: "Willow", type: nil, sub_type: nil, img_src: "./../app/assets/images/41.png")
Card.create(suit: "Willow", type: "Ribbon", sub_type: nil, img_src: "./../app/assets/images/42.png")
Card.create(suit: "Willow", type: "Animal", sub_type: nil, img_src: "./../app/assets/images/43.png")
Card.create(suit: "Willow", type: "Bright", sub_type: "Rain Man", img_src: "./../app/assets/images/44.png")
Card.create(suit: "Paulownia", type: nil, sub_type: nil, img_src: "./../app/assets/images/45.png")
Card.create(suit: "Paulownia", type: nil, sub_type: nil, img_src: "./../app/assets/images/46.png")
Card.create(suit: "Paulownia", type: nil, sub_type: nil, img_src: "./../app/assets/images/47.png")
Card.create(suit: "Paulownia", type: "Bright", sub_type: nil, img_src: "./../app/assets/images/48.png")
