# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
PATHH = "./../hanafuda-back-end"
Card.destroy_all

Card.create(suit: "Pine", nature: nil, sub_nature: nil, img_src: "#{PATHH}/app/assets/images/1.png")
Card.create(suit: "Pine", nature: nil, sub_nature: nil, img_src: "#{PATHH}/app/assets/images/2.png")
Card.create(suit: "Pine", nature: "Ribbon", sub_nature: "Poem", img_src: "#{PATHH}/app/assets/images/3.png")
Card.create(suit: "Pine", nature: "Bright", sub_nature: nil, img_src: "#{PATHH}/app/assets/images/4.png")
Card.create(suit: "Plum Blossoms", nature: nil, sub_nature: nil, img_src: "#{PATHH}/app/assets/images/5.png")
Card.create(suit: "Plum Blossoms", nature: nil, sub_nature: nil, img_src: "#{PATHH}/app/assets/images/6.png")
Card.create(suit: "Plum Blossoms", nature: "Ribbon", sub_nature: "Poem", img_src: "#{PATHH}/app/assets/images/7.png")
Card.create(suit: "Plum Blossoms", nature: "Animal", sub_nature: nil, img_src: "#{PATHH}/app/assets/images/8.png")
Card.create(suit: "Cherry Blossoms", nature: nil, sub_nature: nil, img_src: "#{PATHH}/app/assets/images/9.png")
Card.create(suit: "Cherry Blossoms", nature: nil, sub_nature: nil, img_src: "#{PATHH}/app/assets/images/10.png")
Card.create(suit: "Cherry Blossoms", nature: "Ribbon", sub_nature:"Poem", img_src: "#{PATHH}/app/assets/images/11.png")
Card.create(suit: "Cherry Blossoms", nature: "Bright", sub_nature: nil, img_src: "#{PATHH}/app/assets/images/12.png")
Card.create(suit: "Wisteria", nature: nil, sub_nature: nil, img_src: "#{PATHH}/app/assets/images/13.png")
Card.create(suit: "Wisteria", nature: nil, sub_nature: nil, img_src: "#{PATHH}/app/assets/images/14.png")
Card.create(suit: "Wisteria", nature: "Ribbon", sub_nature: nil, img_src: "#{PATHH}/app/assets/images/15.png")
Card.create(suit: "Wisteria", nature: "Animal", sub_nature: nil, img_src: "#{PATHH}/app/assets/images/16.png")
Card.create(suit: "Iris", nature: nil, sub_nature: nil, img_src: "#{PATHH}/app/assets/images/17.png")
Card.create(suit: "Iris", nature: nil, sub_nature: nil, img_src: "#{PATHH}/app/assets/images/18.png")
Card.create(suit: "Iris", nature: "Ribbon", sub_nature: nil, img_src: "#{PATHH}/app/assets/images/19.png")
Card.create(suit: "Iris", nature: "Animal", sub_nature: nil, img_src: "#{PATHH}/app/assets/images/20.png")
Card.create(suit: "Peony", nature: nil, sub_nature: nil, img_src: "#{PATHH}/app/assets/images/21.png")
Card.create(suit: "Peony", nature: nil, sub_nature: nil, img_src: "#{PATHH}/app/assets/images/22.png")
Card.create(suit: "Peony", nature: "Ribbon", sub_nature: "Blue", img_src: "#{PATHH}/app/assets/images/23.png")
Card.create(suit: "Peony", nature: "Animal", sub_nature: "Butterfly", img_src: "#{PATHH}/app/assets/images/24.png")
Card.create(suit: "Bush Clover", nature: nil, sub_nature: nil, img_src: "#{PATHH}/app/assets/images/25.png")
Card.create(suit: "Bush Clover", nature: nil, sub_nature: nil, img_src: "#{PATHH}/app/assets/images/26.png")
Card.create(suit: "Bush Clover", nature: "Ribbon", sub_nature: nil, img_src: "#{PATHH}/app/assets/images/27.png")
Card.create(suit: "Bush CLover", nature: "Animal", sub_nature: "boar", img_src: "#{PATHH}/app/assets/images/28.png")
Card.create(suit: "Silver Grass", nature: nil, sub_nature: nil, img_src: "#{PATHH}/app/assets/images/29.png")
Card.create(suit: "Silver Grass", nature: nil, sub_nature: nil, img_src: "#{PATHH}/app/assets/images/30.png")
Card.create(suit: "Silver Grass", nature: "Animal", sub_nature: nil, img_src: "#{PATHH}/app/assets/images/31.png")
Card.create(suit: "Silver Grass", nature: "Bright", sub_nature: nil, img_src: "#{PATHH}/app/assets/images/32.png")
Card.create(suit: "Chrysanthemum", nature: nil, sub_nature: nil, img_src: "#{PATHH}/app/assets/images/33.png")
Card.create(suit: "Chrysanthemum", nature: nil, sub_nature: nil, img_src: "#{PATHH}/app/assets/images/34.png")
Card.create(suit: "Chrysanthemum", nature: "Ribbon", sub_nature: "blue", img_src: "#{PATHH}/app/assets/images/35.png")
Card.create(suit: "Chrysanthemum", nature: "Animal", sub_nature: nil, img_src: "#{PATHH}/app/assets/images/36.png")
Card.create(suit: "Maple", nature: nil, sub_nature: nil, img_src: "#{PATHH}/app/assets/images/37.png")
Card.create(suit: "Maple", nature: nil, sub_nature: nil, img_src: "#{PATHH}/app/assets/images/38.png")
Card.create(suit: "Maple", nature: "Ribbon", sub_nature: "Blue", img_src: "#{PATHH}/app/assets/images/39.png")
Card.create(suit: "Maple", nature: "Animal", sub_nature: "Deer", img_src: "#{PATHH}/app/assets/images/40.png")
Card.create(suit: "Willow", nature: nil, sub_nature: nil, img_src: "#{PATHH}/app/assets/images/41.png")
Card.create(suit: "Willow", nature: "Ribbon", sub_nature: nil, img_src: "#{PATHH}/app/assets/images/42.png")
Card.create(suit: "Willow", nature: "Animal", sub_nature: nil, img_src: "#{PATHH}/app/assets/images/43.png")
Card.create(suit: "Willow", nature: "Bright", sub_nature: "Rain Man", img_src: "#{PATHH}/app/assets/images/44.png")
Card.create(suit: "Paulownia", nature: nil, sub_nature: nil, img_src: "#{PATHH}/app/assets/images/45.png")
Card.create(suit: "Paulownia", nature: nil, sub_nature: nil, img_src: "#{PATHH}/app/assets/images/46.png")
Card.create(suit: "Paulownia", nature: nil, sub_nature: nil, img_src: "#{PATHH}/app/assets/images/47.png")
Card.create(suit: "Paulownia", nature: "Bright", sub_nature: nil, img_src: "#{PATHH}/app/assets/images/48.png")
